### ISSUE TITLE
Won't compile: Undefined symbols x86_64

### ISSUE THREAD

**Issue by stromgren** [lp/ObjCHiredis#1]
I try to compile my project and get the following error:

> Undefined symbols for architecture x86_64:
>  "_OBJC_CLASS_$_ObjCHiredis", referenced from:
>      objc-class-ref in AppDelegate.o
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

My project is set to 64-bit. 

I've also tried to compile the framework from source, but it gives the same error when i include it in the project.

Am I missing some build settings?

**Comment by lp** [comment]
Have you tried to download the latest compiled framework from the download section of the project?
https://github.com/downloads/lp/ObjCHiredis/ObjCHiredis_OSX_1o3o9.zip
I can confirm it is built for the x86_64 arch.
